language: go

go:
  - 1.8.x

services:
  - mongodb
  - redis-server

install:
  - sudo add-apt-repository ppa:masterminds/glide && sudo apt-get update
  - sudo apt-get install glide
  - make install-deps

script:
  - cp goworld.ini.sample goworld.ini
  - python goworld.py build dispatcher gate test_game chatroom_demo
  - make test
  - python goworld.py start test_game
  - sleep 1
  - python goworld.py reload
  - sleep 1
  - python goworld.py stop

