language: go

go:
  - 1.8.x


env:
  - TRAVIS=1

services:
  - mysql
  - mongodb
  - redis-server

before_install:
  - GLIDE_OS_ARCH=`go env GOHOSTOS`-`go env GOHOSTARCH`
  - GLIDE_TAG=$(curl -s https://glide.sh/version)
  - GLIDE_LATEST_RELEASE_URL="https://github.com/Masterminds/glide/releases/download/${GLIDE_TAG}/glide-${GLIDE_TAG}-${GLIDE_OS_ARCH}.tar.gz"
  - wget ${GLIDE_LATEST_RELEASE_URL} -O /tmp/glide.tar.gz
  - mkdir /tmp/glide
  - tar --directory=/tmp/glide -xvf /tmp/glide.tar.gz
  - export PATH=$PATH:/tmp/glide/${GLIDE_OS_ARCH}

  - mysql -e 'CREATE DATABASE goworld;'

install:
  - pip install psutil
  - glide install

script:
  - cp goworld.ini.sample goworld.ini
  - python goworld.py build dispatcher gate test_game chatroom_demo
  - make test
  - python goworld.py start test_game
  - sleep 1
  - python goworld.py reload
  - sleep 1
  - python goworld.py stop

