language: go

go:
  - 1.8.x

services:
  - mongodb
  - redis-server

install:
  - make install-deps
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - python goworld.py build dispatcher gate test_game chatroom_demo
  - python goworld.py start test_game
  - sleep 1
  - python goworld.py freeze
  - sleep 1
  - python goworld.py restore test_game
  - sleep 1
  - python goworld.py stop
  - make test

