language: go

go:
  - 1.8.x

install:
  - go get github.com/xiaonanln/go-xnsyncutil/xnsyncutil
  - go get github.com/xiaonanln/goTimer
  - go get github.com/xiaonanln/typeconv
  - go get golang.org/x/net/context
  - go get github.com/Sirupsen/logrus
  - go get github.com/garyburd/redigo/redis
  - go get github.com/google/btree
  - go get github.com/pkg/errors
  - go get golang.org/x/net/websocket
  - go get gopkg.in/eapache/queue.v1
  - go get gopkg.in/ini.v1
  - go get gopkg.in/mgo.v2
  - go get gopkg.in/vmihailenco/msgpack.v2
  - go get gopkg.in/natefinch/lumberjack.v2