language: go

go:
  - 1.8.x

services:
  - mongodb
  - redis-server

install:
  - make deps
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - make
  - make test

